### ISSUE TITLE
Invoice Configs

### ISSUE THREAD

**Issue by AndresPrez** [h1dd3nsn1p3r/pdf-invoice#25]
Hi @h1dd3nsn1p3r, nice tool. I've been trying it out and it looks very nice.

Is there a way to make tax sections and the due date optional?

**Comment by h1dd3nsn1p3r** [comment]
Hi @AndresPrez 

Don't have that option for now. 

Please pass `"0"` in tax value and the same day will be applied if you do not pass a due date.

**Comment by AndresPrez** [comment]
thanks for the quick response and short term solution ❤️
