### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by zaynekomichi** [h1dd3nsn1p3r/pdf-invoice#31]
As noted the fs package does not work in the browser. I suggest making a browser version of the package

```
Uncaught Error: Dynamic require of "fs" is not supported

```

**Comment by h1dd3nsn1p3r** [comment]
Hi @zaynekomichi 

I created this package for node and bun environments. I am not sure if I will be having the client side implementation of this package.

However, I already have the API version of this package which uses Hono and bun runtime. Do you want to have a look at that? Do you think should I open-source it too and add link in the README?

**Comment by zaynekomichi** [comment]
That would be great,. A readme would go a long way in helping newbies, also would like to contribute to the project!
