### ISSUE TITLE
Add field for IBAN

### ISSUE THREAD

**Issue by 11mb** [h1dd3nsn1p3r/pdf-invoice#32]
Is there a way to put the bank account number, or IBAN nr also?

Thanks!

**Comment by h1dd3nsn1p3r** [comment]
Hi @11mb

Where would you like to have IBAN? In the company section or bill to section?

**Comment by 11mb** [comment]
Thanks for your fast response @h1dd3nsn1p3r.
In the company section. In europe it is common to add it there so the receiver knows where the money can be transferred to.

Thanks!

**Comment by h1dd3nsn1p3r** [comment]
Hi @11mb 

Added: bank/IBAN in the company section. https://github.com/h1dd3nsn1p3r/pdf-invoice/pull/33

This is how you add bank/IBAN in your payload.

```
const payload = {
  ...
  company: {
      logo: "<svg>...</svg>", // Optional. SVG logo of your company.
      name: "Festrol Corp.",
      address: "1711 W. El Segundo Blvd, Hawthorne, Canada - 90250",
      phone: "Tel: (+11) 245 543 903",
      email: "Mail: hello@festrol.io",
      website: "Web: https://www.festrolcorp.io",
      taxId: "Tax ID: 1234567890", // Optional.
      bank: "IBAN: 1234567890AC", // Optional.
  },
  ...
}
```
